name: AutoLogin
on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:    
      - main
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Dummy input
        options: 
        - foo
        - bar
jobs:
  do-auto-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.5.0'
      - run: npm install
      - name: Autologin Script
        env: 
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
          PINS: ${{ secrets.PINS }}
          BROKERS: ${{ secrets.BROKERS }}
          SECURITY_QUESTIONS1: ${{ secrets.SECURITY_QUESTIONS1 }}
          SECURITY_QUESTIONS2: ${{ secrets.SECURITY_QUESTIONS2 }}
        run: CHROMIUM_BIN=$(which chrome) npm run start
